name: darto_template
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  bcrypt: ^1.1.3
  crypto: ^3.0.6
  dart_jsonwebtoken: ^3.2.0
  darto: ^0.0.31
  dotenv: ^4.2.0
  get_it: ^8.2.0
  intl: ^0.20.2
  jiffy: ^6.4.3
  mongo_dart: ^0.10.5
  path: ^1.9.1
  result_dart: ^2.1.1
  swagger_ui_darto: ^0.0.1
  zard: ^0.0.18
  zard_darto_middleware: ^0.0.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
